apiVersion: v1
kind: Service
metadata:
  name: api-production-service
spec:
  selector:
    app: api-production
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31002
  type: LoadBalancer
