apiVersion: v1
kind: Secret
metadata:
  name: api-production-secrets
type: Opaque
data:
  PORT: MzAwMA==
  REDIS_HOST: ZGItYXBpLXByb2R1Y3Rpb24tc2VydmljZQ==
  RABBITMQ_URL: YW1xcHM6Ly9wa2l6ZXF0bjpCcXVxWFpXdms5WlRMYXJ6Yl9UYlMzY0l3OGtvdG82cEB3b29kcGVja2VyLnJtcS5jbG91ZGFtcXAuY29tL3BraXplcXRu

