apiVersion: v1
kind: Service
metadata:
  name: db-api-production-service
spec:
  type: ClusterIP
  selector:
    app: api-production-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
